### ISSUE TITLE
ImportError: No module named tbdata.export

### ISSUE THREAD

**Issue by turbolego** [DrHibbitts/TiltBrushConverter#2]
> Microsoft Windows [Version 10.0.16299.125]
>(c) 2017 Microsoft Corporation. All rights reserved.

>C:\WINDOWS\system32>D:

>D:\>cd D:\Downloads\TiltBrushConverter-master

>D:\Downloads\TiltBrushConverter-master>python TiltBrushConverter.py
>Traceback (most recent call last):
>  File "TiltBrushConverter.py", line 31, in convertOBJs
>    import OBJConverterGui
>  File "D:\Downloads\TiltBrushConverter-master\OBJConverterGui.py", line 7, in <module>
>    import convert_to_obj
>  File "D:\Downloads\TiltBrushConverter-master\convert_to_obj.py", line 50, in <module>
>    from tbdata.export import iter_meshes, TiltBrushMesh, SINGLE_SIDED_FLAT_BRUSH
>ImportError: No module named tbdata.export

Please advise.

**Comment by SatishGodaPearl** [comment]
I am facing the same error too. How to get the tbdata module?

**Comment by SatishGodaPearl** [comment]
Well, looking at the following file, I think the solution lies in updating the tbdata import with its new destination in an another repository.

C:\Program Files (x86)\Steam\steamapps\common\Tilt Brush\Support\README.txt

```
As of 10.3.16, support scripts have been open-sourced, and now live here:
https://github.com/googlevr/tilt-brush-toolkit

Thank you.
```

**Comment by XanderBos** [comment]
I know this is from two years ago but did any of you find a solution for this? I cannot get exports in fbx from my build from open brush and want to convert the Json files this way.
